import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Roboto } from 'next/font/google';
export const roboto = Roboto({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full`}
    >
      <body className={`${roboto.className} antialiased min-h-full flex flex-col`}>
        <Navbar/>
        <div className="mx-auto px-4 bg h-full w-full">
          {children}
        </div>
        </body>
    </html>
  );
}
